/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotFoundImport } from './routes/not-found'
import { Route as FlightsImport } from './routes/flights'
import { Route as BadRequestImport } from './routes/bad-request'
import { Route as AddFlightImport } from './routes/add-flight'
import { Route as IndexImport } from './routes/index'
import { Route as EditFlightIdImport } from './routes/edit-flight.$id'

// Create/Update Routes

const NotFoundRoute = NotFoundImport.update({
  path: '/not-found',
  getParentRoute: () => rootRoute,
} as any)

const FlightsRoute = FlightsImport.update({
  path: '/flights',
  getParentRoute: () => rootRoute,
} as any)

const BadRequestRoute = BadRequestImport.update({
  path: '/bad-request',
  getParentRoute: () => rootRoute,
} as any)

const AddFlightRoute = AddFlightImport.update({
  path: '/add-flight',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EditFlightIdRoute = EditFlightIdImport.update({
  path: '/edit-flight/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/add-flight': {
      id: '/add-flight'
      path: '/add-flight'
      fullPath: '/add-flight'
      preLoaderRoute: typeof AddFlightImport
      parentRoute: typeof rootRoute
    }
    '/bad-request': {
      id: '/bad-request'
      path: '/bad-request'
      fullPath: '/bad-request'
      preLoaderRoute: typeof BadRequestImport
      parentRoute: typeof rootRoute
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsImport
      parentRoute: typeof rootRoute
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundImport
      parentRoute: typeof rootRoute
    }
    '/edit-flight/$id': {
      id: '/edit-flight/$id'
      path: '/edit-flight/$id'
      fullPath: '/edit-flight/$id'
      preLoaderRoute: typeof EditFlightIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AddFlightRoute,
  BadRequestRoute,
  FlightsRoute,
  NotFoundRoute,
  EditFlightIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/add-flight",
        "/bad-request",
        "/flights",
        "/not-found",
        "/edit-flight/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/add-flight": {
      "filePath": "add-flight.tsx"
    },
    "/bad-request": {
      "filePath": "bad-request.tsx"
    },
    "/flights": {
      "filePath": "flights.tsx"
    },
    "/not-found": {
      "filePath": "not-found.tsx"
    },
    "/edit-flight/$id": {
      "filePath": "edit-flight.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
